import sys
import os
import sqlite3
import warnings

# Suppress specific DeprecationWarning from langgraph
warnings.filterwarnings("ignore", category=DeprecationWarning, module="langgraph")

# Setup the path to ensure imports work correctly from the root directory
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from langgraph.checkpoint.sqlite import SqliteSaver
from agents.supervisor import build_team_graph
from ingestion.teaching_engine import teach_single
from agents.batch_analyzer import analyze_log_file_in_batches

def extract_clean_text(content):
    """
    Helper function to extract clean text from complex response objects.
    Safely handles strings, lists, and nested dictionaries.
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        for item in content:
            if isinstance(item, dict) and item.get("type") == "text":
                return item.get("text")
    return str(content)

def main():
    # Create SQLite connection for persistent memory across sessions
    conn = sqlite3.connect('memory.db', check_same_thread=False)
    # Initialize checkpointer
    memory = SqliteSaver(conn)

    # Build the Multi-Agent Graph and attach the memory
    agent_app = build_team_graph(memory=memory)

    # Define the config dict for the conversation thread
    config = {'configurable': {'thread_id': 'session_1'}}

    print('\n🚀 Welcome to the LogAnalyzer AI. Type "exit" to quit.')

    while True:
        try:
            user_input = input('\n🧑‍💻 You: ')
        except EOFError:
            break

        if user_input.lower() in ['exit', 'quit']:
            break

        # --- Batch Analysis Mode ---
        if user_input.strip().lower() == 'analyze all':
            file_path = input("📂 Enter log file path to analyze: ").strip()
            chunk_input = input("🔢 Enter chunk size (default 50): ").strip()
            
            try:
                chunk_size = int(chunk_input) if chunk_input else 50
            except ValueError:
                print("Invalid chunk size. Defaulting to 50.")
                chunk_size = 50

            print(f"\n🚀 Starting Batch Analysis on {file_path}...")
            summary = analyze_log_file_in_batches(file_path, chunk_size=chunk_size)
            
            print(f"\n📊 === EXECUTIVE SUMMARY ===\n{summary}\n===========================\n")
            continue

        # --- Teaching Engine Mode ---
        if user_input.strip().lower() == 'teach':
            try:
                file_path = input("📂 Enter log file path: ")
                start = int(input("🔢 Enter start line: "))
                end = int(input("🔢 Enter end line: "))
                status = input("🏷️ Enter status (golden/anomaly): ")
                explanation = input("🧠 Enter your human explanation: ")

                save_stats_input = input("📊 Save to statistics DB too? (y/n): ")
                save_to_stats = save_stats_input.strip().lower() == 'y'
                log_type = None
                if save_to_stats:
                    log_type = input("📊 Enter log type (e.g., app_logs): ").strip()

                result = teach_single(file_path, start, end, status, explanation, save_to_stats=save_to_stats, log_type=log_type)
                print(f"\n{result}")
            except ValueError:
                print("\nError: Please enter valid numbers for start/end lines.")
            continue

        # --- Multi-Agent Investigation Flow ---
        # The graph routes the user input automatically: START -> Baseline -> Investigator -> END
        response = agent_app.invoke({"messages": [("user", user_input)]}, config=config)

        # Extract the final answer from the last message generated by the Investigator Agent
        raw_content = response["messages"][-1].content
        clean_text = extract_clean_text(raw_content)

        print(f'\n🤖 DevOps AI:\n{clean_text}')

if __name__ == "__main__":
    main()