from typing import TypedDict, Annotated, Sequence
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    """
    Represents the shared state of the multi-agent system.
    """
    # The history of messages in the conversation
    messages: Annotated[Sequence[BaseMessage], add_messages]
    
    # The rulebook generated by the Baseline Specialist
    baseline_profile: str
    
    # The final report from the Investigator Agent (for future use)
    investigation_report: str
    
    # The next node to route to, controlled by the Supervisor
    next_node: str